### ISSUE TITLE
Collision

### ISSUE THREAD

**Issue by N3RDL1F3** [cjddmut/Unity-2D-Platformer-Controller#11]
Hello!

Great script! It has alot of usefull features. Although I am having some trouble getting the collision to work. I put some platforms on my scene, set thier layer to "platforms", and on the PlatformerMotor2D I set the enviroment layer also to "platforms" but there is no collision and the player just falls.

I am using your prefab with a custom sprite inside it.

Any help would be awesome!

Cheers

**Comment by cjddmut** [comment]
@N3RDL1F3  Hey, this is just for regular environments and not moving platforms correct? Make sure the platforms all have a BoxCollider2D or EdgeCollider2Ds attached.

Let me know if that doesn't solve your problem!

C.J.

**Comment by N3RDL1F3** [comment]
Hi C.J,

Yeah I actually saw that about 30 minutes after I wrote you that I had a
BoxCollider instead of a BoxCollider2D on the platforms -.-*. Sorry for
bothering you!

Great script though still working through all the functions but its a great
starting point for me.

Have a nice day,

Aaron

2015-05-05 18:42 GMT+02:00 C.J. Kimberlin notifications@github.com:

**Comment by cjddmut** [comment]
:)

I can probably be more description in the setup instructions though!
