### ISSUE TITLE
Scale X flip breaks collision on slopes

### ISSUE THREAD

**Issue by thelucre** [cjddmut/Unity-2D-Platformer-Controller#22]
I saw this before the animation demo was added to the repo. It appears that flipping the Transform with the PlatformerMotor2d script will sometimes push the character through the ground on slopes. My tests have multiple slope angles (1/2 and 1/3 slopes) which may be where the issues is coming from. 

I solved this by flipping the visual child transform instead, but it would be nice to flip the entire parent.

**Comment by cjddmut** [comment]
Flipping the parent's x scale on the transform seems to work ok. Though I suspect if collider was off center then it might break. Is that the issue?

**Comment by thelucre** [comment]
Ah that was it. Duly noted, thanks!
