### ISSUE TITLE
Where to set 'static environment layer mask'

### ISSUE THREAD

**Issue by neutt22** [cjddmut/Unity-2D-Platformer-Controller#27]
New to Unity. I want to use this script so my player won't slide down slopes when they stop moving halfway.

Thanks!

**Comment by cjddmut** [comment]
![picture1](https://cloud.githubusercontent.com/assets/2998383/8423644/485b8d64-1ea1-11e5-9a36-2dc3d20f4470.png)

Also if you're character is sliding then change the degree it is allowed to be on the slope. Checkout the readme file for full documentation.

**Comment by RuneShiStorm** [comment]
My character is just fallow through all collision boxes.. Any idea what yo do?
