### ISSUE TITLE
Help setting up?

### ISSUE THREAD

**Issue by Simplicitydown** [cjddmut/Unity-2D-Platformer-Controller#36]
I apologize if this seems over simplistic but I cannot figure out how to open or apply this project at all...A minor tutorial for the skill-inept would be really useful. I cannot drop the prefab into a scene, it just won't allow it. Would it be easiest and is there a way to just import all of your animations into an original scene and apply all scripting to it?
Thank you!

P.S. sorry again if this is too obvious a question, but me and my wife have been running into brick walls attempting 2d game developing as a hobby for 2 years now and this could really be the breakthrough we need.

**Comment by cjddmut** [comment]
Are you getting an error when trying to drop the prefab into the scene?

**Comment by llafuente** [comment]
as a simple test, try to open directly this project into unity, then you can try to import it to an existing one... it should be just copy "PC2D" into your project...

**Comment by Simplicitydown** [comment]
Thanks again for the help. This is what is happening. Going to 'open new project,' and selecting the 'Unity 2d platform controller develop' folder opens a project with this message in the console and a blank screen: Assets/PC2D/Scripts/PlatformerMotor2D.cs(2873,35): error CS1061: Type `UnityEngine.Collider2D' does not contain a definition for`usedByEffector' and no extension method `usedByEffector' of type`UnityEngine.Collider2D' could be found (are you missing a using directive or an assembly reference?)

Trying to drop 'Basic Player Controller.prefab' into this project or any other existing one does not give an error message, it simply turns the mouse into the 'no' symbol and leaves me with nothing. Should I not have to delete all of my scripts that currently move the player before these would even take over? Or should I try making a basic scene with a sprite from scratch and somehow trying to get it into that instead? Perhaps something in my game that is pre-existing is causing this? Trying to export the project into my project makes the folder appear in the assets, but still cannot drop the prefab into the scene, still just the no symbol.

Hope that helps, I appreciate it.

**Comment by cjddmut** [comment]
It sounds like you're using an older version of Unity. For PC2D you'll need to update to the latest version or go modify the source.

**Comment by Simplicitydown** [comment]
Finally got the bandwidth to dl Unity 5 (Limited rural usage) and it turns out your suggestion was right that upgrading was the key. Sorry to waste your time on such paltry issues!
