### ISSUE TITLE
Can't seem to shut off Wall Grabs

### ISSUE THREAD

**Issue by slanger001** [cjddmut/Unity-2D-Platformer-Controller#47]
Can't seem to turn off Wall Grabs- could this be an issue with the latest Unity release.  Thanks :)

**Comment by cjddmut** [comment]
Very possibly. Try turning off slopes and see if the problem persists.

**Comment by slanger001** [comment]
Thanks for the idea.  I made sure slopes were off and it still occurs. Thanks also for the quick response.

**Comment by cjddmut** [comment]
Well that was the quickest idea I could have :) The only suggestions I can really give are the more obvious ones, such as make sure "Enable Wall Sticks" is unchecked, or if it is checked, then "Wall Stick Duration" is a small value. If those aren't the issue then I'll have to ask if ya can package up a simple example of it failing and send it to me (along with your unity version).

**Comment by cjddmut** [comment]
This should be fixed now.
