### ISSUE TITLE
Missing definition

### ISSUE THREAD

**Issue by 31emanual** [cjddmut/Unity-2D-Platformer-Controller#50]
When I boot up Unity 3D, this error appears in the console:Assets/PC2D/Editor/PlatformerMotor2DEditor.cs(349,24): error CS0117: `UnityEngine.Physics2D' does not contain a definition for`queriesStartInColliders'

**Comment by cjddmut** [comment]
What version of Unity do you have?

**Comment by 31emanual** [comment]
Unity 5.1.1f1 64-bit

**Comment by cjddmut** [comment]
Most likely that variable was introduced in 5.2...you can update to that version (I don't suggest 5.3 at the moment) or look up what the query used to be called in 5.1 and replace that line.
