### ISSUE TITLE
[Request] Modify dash gravity scale

### ISSUE THREAD

**Issue by ordiovince** [cjddmut/Unity-2D-Platformer-Controller#53]
Hello,

Is it possible that you add a property to modify the gravity scale during the dash?
In our project we want the player to be affected by gravity while he is dashing.

Thanks.

**Comment by cjddmut** [comment]
It would take some modifying the underlying source code. You can try just setting velocity instead of dashing to see if that'll do what you want it to.

**Comment by ordiovince** [comment]
I'll try, thanks.

Just a question for you, do you use the Layer Collision Matrix defined on the Unity Physics2D settings to handle collision checks or not?

**Comment by cjddmut** [comment]
No, I explored that for a bit but since I just boxcasts instead of using the physics engine it's just defined in the motor inspector.
