### ISSUE TITLE
Delay between input and movement starting

### ISSUE THREAD

**Issue by Anesthesius** [cjddmut/Unity-2D-Platformer-Controller#54]
I seem to be having an issue where the standard 'Basic Platformer Controller' prefab has a noticable delay between input and movement. This isn't particularly noticeable when you're in the air (edit: actually, it sort-of is if you start with a standstill jump, then start holding a direction midair), but when you start from a dead stand-still, there's a good amount of time where you're holding the button, but having started moving yet.

I know that's not much to go on, so let me know if there's anything more I can provide to help. 

This is an awesome controller. Has everything you could want - power-curve jumps, doublejumps, wall-slides, wall-jumps, etc. And tons of great information too.

EDIT: Aha - INPUT_THRESHOLD in globals. I thought I checked that file before submitting this - sorry!

**Comment by cjddmut** [comment]
That threshold is meant to prevent a deadzone from triggering moment. That can be set to 0 if you're confident that your input model (unity or whatever) handles that issue.
