### ISSUE TITLE
Where are conrtols handled?

### ISSUE THREAD

**Issue by SandeMC** [cjddmut/Unity-2D-Platformer-Controller#82]
I can't seem to find where can I change controls to my own?

**Comment by SandeMC** [comment]
Okay, I need some help. I guess the controls are handled in Globals.cs. How can I make it read the float value from my UI controller and read it as a string?

**Comment by cjddmut** [comment]
It's been awhile since I looked at this package but if memory serves the
controlling aspect is something you could roll your own on. The important
part is the motor. If you're trying to interface with the motor in a
different way you'll have to rewrite the controller (which isn't much).

**Comment by SandeMC** [comment]
Actually, I figured that out myself. I had to use PlayerController2D.cs,
reference the joystick in it and just change axises with the joystick ones.
For buttons it was a bit more complicated - I had to create new voids, but
the result came out pretty much what I wanted.

вт, 25 авг. 2020 г., 23:12 C.J. Kimberlin <notifications@github.com>:

> It's been awhile since I looked at this package but if memory serves the
> controlling aspect is something you could roll your own on. The important
> part is the motor. If you're trying to interface with the motor in a
> different way you'll have to rewrite the controller (which isn't much).
>
